In [1]:
import pandas as pd
from typing import List, Dict, Any, Union
#from statsbombpy import sb
import numpy as np
import json
import re
#N(reaS^!.sTijg7

In [3]:
def extract_matches_to_dataframe(match_data_list: List[List]) -> pd.DataFrame:
    """
    Extract match information from nested lists and convert to a pandas DataFrame.
    
    Expected structure for each match:
    [competition_info, datetime, season, teams_dict, home_events_list, away_events_list]
    
    Args:
        match_data_list: List of lists, where each inner list represents a match
    
    Returns:
        pandas.DataFrame with all match and event information
    """
    all_rows = []
    
    for match_idx, match in enumerate(match_data_list):
        try:
            # Extract basic match information
            competition = match[0] if len(match) > 0 else None
            datetime_str = match[1] if len(match) > 1 else None
            season = match[2] if len(match) > 2 else None
            teams = match[3] if len(match) > 3 and isinstance(match[3], dict) else {}
            
            # Extract team information
            home_team = teams.get('home', None)
            away_team = teams.get('away', None)
            
            # Process events (home and away)
            events_lists = match[4:] if len(match) > 4 else []
            
            # If no events, create one row with match info only
            if not any(events_lists):
                row = {
                    'match_id': match_idx,
                    'competition': competition,
                    'datetime': datetime_str,
                    'season': season,
                    'home_team': home_team,
                    'away_team': away_team,
                    'event_type': None,
                    'time': None,
                    'player': None,
                    'team_side': None,
                    'score': None,
                    'assist': None,
                    'player_in': None,
                    'player_out': None,
                    'reason': None,
                    'event_source': None
                }
                all_rows.append(row)
            else:
                # Process each events list (typically home and away)
                for list_idx, events_list in enumerate(events_lists):
                    if not isinstance(events_list, list):
                        continue
                        
                    team_side = 'home' if list_idx == 0 else 'away'
                    
                    # If events list is empty, create one row for this team
                    if not events_list:
                        row = {
                            'match_id': match_idx,
                            'competition': competition,
                            'datetime': datetime_str,
                            'season': season,
                            'home_team': home_team,
                            'away_team': away_team,
                            'event_type': None,
                            'time': None,
                            'player': None,
                            'team_side': team_side,
                            'score': None,
                            'assist': None,
                            'player_in': None,
                            'player_out': None,
                            'reason': None,
                            'event_source': f'list_{list_idx}'
                        }
                        all_rows.append(row)
                        continue
                    
                    # Process each event in the list
                    for event in events_list:
                        if not isinstance(event, dict):
                            continue
                            
                        # Create base row with match information
                        row = {
                            'match_id': match_idx,
                            'competition': competition,
                            'datetime': datetime_str,
                            'season': season,
                            'home_team': home_team,
                            'away_team': away_team,
                            'team_side': team_side,
                            'event_source': f'list_{list_idx}'
                        }
                        
                        # Extract event information with flexible key handling
                        row['event_type'] = event.get('type', None)
                        row['time'] = event.get('time', None)
                        row['player'] = event.get('player', None)
                        row['score'] = event.get('score', None)
                        row['assist'] = event.get('assist', None)
                        row['player_in'] = event.get('player_in', None)
                        row['player_out'] = event.get('player_out', None)
                        row['reason'] = event.get('reason', None)
                        
                        # Override team_side if specified in event
                        if 'team' in event:
                            row['team_side'] = event['team']
                        
                        # Add any additional keys that might exist
                        for key, value in event.items():
                            if key not in ['type', 'time', 'player', 'score', 'assist', 
                                         'player_in', 'player_out', 'reason', 'team']:
                                row[f'extra_{key}'] = value
                        
                        all_rows.append(row)
                        
        except Exception as e:
            print(f"Error processing match {match_idx}: {e}")
            continue
    
    # Convert to DataFrame
    df = pd.DataFrame(all_rows)
    
    # Reorder columns for better readability
    base_columns = ['match_id', 'competition', 'datetime', 'season', 'home_team', 'away_team', 
                   'team_side', 'event_source', 'event_type', 'time', 'player', 'score', 
                   'assist', 'player_in', 'player_out', 'reason']
    
    # Add any extra columns that were found
    extra_columns = [col for col in df.columns if col.startswith('extra_')]
    final_columns = base_columns + extra_columns
    
    # Only include columns that exist in the DataFrame
    final_columns = [col for col in final_columns if col in df.columns]
    
    return df[final_columns]


def analyze_match_data(df: pd.DataFrame) -> Dict[str, Any]:
    """
    Provide a summary analysis of the extracted match data.
    
    Args:
        df: DataFrame returned by extract_matches_to_dataframe
    
    Returns:
        Dictionary with analysis summary
    """
    analysis = {
        'total_matches': df['match_id'].nunique(),
        'total_events': len(df[df['event_type'].notna()]),
        'competitions': df['competition'].unique().tolist(),
        'seasons': df['season'].unique().tolist(),
        'event_types': df['event_type'].value_counts().to_dict(),
        'teams': sorted(set(df['home_team'].dropna().tolist() + df['away_team'].dropna().tolist())),
        'date_range': {
            'earliest': df['datetime'].min(),
            'latest': df['datetime'].max()
        }
    }
    
    return analysis


def process_match_dataframe(df):
    """
    Process an existing DataFrame to:
    1. Split 'competition' column into 'competition' and 'matchweek'
    2. Add 'half_event' column based on 'time' column
    
    Args:
        df: pandas DataFrame with 'competition' and 'time' columns
    
    Returns:
        pandas DataFrame with processed columns
    """
    # Make a copy to avoid modifying the original
    df_processed = df.copy()
    
    # Split competition column
    df_processed = split_competition_column(df_processed)
    
    # Add half_event column
    df_processed = add_half_event_column(df_processed)
    
    return df_processed

def split_competition_column(df):
    """
    Split the 'competition' column into 'competition' and 'matchweek' columns.
    """
    df = df.copy()
    
    # Initialize new columns
    df['matchweek'] = None
    
    # Function to split individual competition strings
    def split_single_competition(comp_str):
        if pd.isna(comp_str) or not isinstance(comp_str, str):
            return comp_str, None
        
        # Common patterns for matchweek information
        patterns = [
            r'^(.+?)\s*-\s*(JORNADA\s+\d+)$',   # "PREMIER LEAGUE - JORNADA 38"
            r'^(.+?)\s*-\s*(MATCHDAY\s+\d+)$',  # "PREMIER LEAGUE - MATCHDAY 38"
            r'^(.+?)\s*-\s*(GAMEWEEK\s+\d+)$',  # "PREMIER LEAGUE - GAMEWEEK 38"
            r'^(.+?)\s*-\s*(WEEK\s+\d+)$',      # "PREMIER LEAGUE - WEEK 38"
            r'^(.+?)\s*-\s*(MD\s*\d+)$',        # "PREMIER LEAGUE - MD38"
            r'^(.+?)\s*-\s*(GW\s*\d+)$',        # "PREMIER LEAGUE - GW38"
            r'^(.+?)\s*-\s*(ROUND\s+\d+)$',     # "PREMIER LEAGUE - ROUND 38"
            r'^(.+?)\s*-\s*(\d+)$',             # "PREMIER LEAGUE - 38"
        ]
        
        for pattern in patterns:
            match = re.match(pattern, comp_str.strip(), re.IGNORECASE)
            if match:
                competition_name = match.group(1).strip()
                matchweek = match.group(2).strip()
                return competition_name, matchweek
        
        # If no pattern matches, return the full string as competition name
        return comp_str.strip(), None
    
    # Apply the splitting function
    split_results = df['competition'].apply(split_single_competition)
    
    # Update the columns
    df['competition'] = [result[0] for result in split_results]
    df['matchweek'] = [result[1] for result in split_results]
    
    return df

def add_half_event_column(df):
    """
    Add 'half_event' column based on the 'time' column.
    """
    df = df.copy()
    
    def determine_half(time_str):
        """
        Determine if an event occurred in the first or second half.
        """
        if pd.isna(time_str) or not isinstance(time_str, str):
            return None
        
        # Extract the base minute from formats like "74'", "45+2'", "90+1'"
        match = re.match(r'(\d+)', str(time_str).strip())
        if not match:
            return None
        
        try:
            minute = int(match.group(1))
            
            # Football halves: 1-45 minutes = First Half, 46+ minutes = Second Half
            if 1 <= minute <= 45:
                return 'First Half'
            elif minute >= 46:
                return 'Second Half'
            else:
                return None
        except ValueError:
            return None
    
    # Add the half_event column
    df['half_event'] = df['time'].apply(determine_half)
    
    return df

def reorder_columns(df):
    """
    Reorder columns for better readability, putting new columns in logical positions.
    """
    # Define preferred column order
    preferred_order = [
        'match_id', 'competition', 'matchweek', 'datetime', 'season', 
        'home_team', 'away_team', 'team_side', 'event_source', 
        'event_type', 'time', 'half_event', 'player', 'score', 
        'assist', 'player_in', 'player_out', 'reason'
    ]
    
    # Get existing columns
    existing_cols = df.columns.tolist()
    
    # Start with preferred columns that exist
    final_order = [col for col in preferred_order if col in existing_cols]
    
    # Add any remaining columns that weren't in the preferred list
    remaining_cols = [col for col in existing_cols if col not in final_order]
    final_order.extend(remaining_cols)
    
    return df[final_order]

In [10]:
for i in range(1,12):
    print(i)

1
2
3
4
5
6
7
8
9
10
11

In [12]:
for i in range(1,12):
    print(i)
    with open(f'data_league{i}.json', 'r', encoding='utf-8') as f:
        read_data = json.load(f)

    df = extract_matches_to_dataframe(read_data)

    df2 = process_match_dataframe(df)

    goals_stats_teams = []

    unique_seasons = list(df2['season'].unique())

    for individual_season in unique_seasons:
        unique_teams = list(df2[df2['season'] == individual_season]['home_team'].unique())
        for individual_team in unique_teams:

            temporal_dict = {}

            home_goals_per_season = len(df2[(df2['home_team'] == individual_team) & (df2['event_type'] == 'goal') & (df2['team_side'] == 'home') & (df2['season'] == individual_season)])
            away_goals_per_season = len(df2[(df2['away_team'] == individual_team) & (df2['event_type'] == 'goal') & (df2['team_side'] == 'away') & (df2['season'] == individual_season)])

            average_goals_per_season = (home_goals_per_season + away_goals_per_season)/((len(unique_teams)-1)*2)

            # first half home season goals scored
            first_half_home_season_goals_scored = len(df2[(df2['home_team'] == individual_team) & (df2['event_type'] == 'goal') & (df2['team_side'] == 'home') & (df2['season'] == individual_season) & (df2['half_event'] == 'First Half')])
            # second half home season goals scored
            second_half_home_season_goals_scored = len(df2[(df2['home_team'] == individual_team) & (df2['event_type'] == 'goal') & (df2['team_side'] == 'home') & (df2['season'] == individual_season) & (df2['half_event'] == 'Second Half')])
            # first half away season goals scored
            first_half_away_season_goals_scored = len(df2[(df2['away_team'] == individual_team) & (df2['event_type'] == 'goal') & (df2['team_side'] == 'away') & (df2['season'] == individual_season) & (df2['half_event'] == 'First Half')])
            # first half away season goals scored
            second_half_away_season_goals_scored = len(df2[(df2['away_team'] == individual_team) & (df2['event_type'] == 'goal') & (df2['team_side'] == 'away') & (df2['season'] == individual_season) & (df2['half_event'] == 'Second Half')])
            # first half season goals average scored
            average_first_half_goals_scored = (first_half_home_season_goals_scored + first_half_away_season_goals_scored)/((len(unique_teams)-1)*2)
            # second half season goals average scored
            average_second_half_goals_scored = (second_half_away_season_goals_scored + second_half_home_season_goals_scored)/((len(unique_teams)-1)*2)

            average_home_game_first_half_goals_scored = first_half_home_season_goals_scored/(len(unique_teams)-1)

            average_home_game_second_half_goals_scored = second_half_home_season_goals_scored/(len(unique_teams)-1)

            average_away_game_first_half_goals_scored = first_half_away_season_goals_scored/(len(unique_teams)-1)

            average_away_game_second_half_goals_scored = second_half_away_season_goals_scored/(len(unique_teams)-1)


            # print(f'season: {individual_season} , team: {individual_team}: home goals: {home_goals_per_season}, away goals: {away_goals_per_season}, average goals: {average_goals_per_season}')
            # print('==============================')
            # print(f'first half all season goals scored: {first_half_home_season_goals_scored + first_half_away_season_goals_scored} second half all season goals scored: {second_half_away_season_goals_scored + second_half_home_season_goals_scored}')
            # print('==============================')
            # print(f'average goals first half: {average_first_half_goals_scored} average goals second half: {average_second_half_goals_scored}')
            # print('==============================')
            # print(f'home game first half goals scored: {first_half_home_season_goals_scored} home game second half goals scored {second_half_home_season_goals_scored}')
            # print('==============================')
            # print(f'average home game first half goals: {average_home_game_first_half_goals_scored} average home game second half goals: {average_home_game_second_half_goals_scored}')
            # print('==============================')
            # print(f'away game first half goals scored:{first_half_away_season_goals_scored}  away game second half goals scored:{second_half_away_season_goals_scored}')
            # print('==============================')
            # print(f'average away game first half goals: {average_away_game_first_half_goals_scored} average away game second half goals: {average_away_game_second_half_goals_scored}')

            temporal_dict.update({'season': individual_season, 'team': individual_team, 'home_goals_season': home_goals_per_season, 'away_goals_season':away_goals_per_season,
                                'average_goals_season':average_goals_per_season, 'first_half_season_goals_scored': first_half_home_season_goals_scored + first_half_away_season_goals_scored,
                                'second_half_season_goals_scored':second_half_away_season_goals_scored + second_half_home_season_goals_scored, 'average_season_first_half_goals_scored':average_first_half_goals_scored,
                                'average_season_second_half_goals_scored':average_second_half_goals_scored,'first_half_home_season_goals_scored':first_half_home_season_goals_scored,
                                'second_half_home_season_goals_scored':second_half_home_season_goals_scored, 'average_home_game_first_half_goals_scored':average_home_game_first_half_goals_scored,
                                'average_home_game_second_half_goals_scored':average_home_game_second_half_goals_scored,'first_half_away_season_goals_scored':first_half_away_season_goals_scored,
                                'second_half_away_season_goals_scored':second_half_away_season_goals_scored,'average_away_game_first_half_goals_scored':average_away_game_first_half_goals_scored,
                                'average_away_game_second_half_goals_scored':average_away_game_second_half_goals_scored})
            print(temporal_dict)
            goals_stats_teams.append(temporal_dict)
    with open(f'goal_stats_league{0}.json', 'w', encoding='utf-8') as f:
            json.dump(temporal_dict, f, ensure_ascii=False, indent=4)    


    i += 1

1
{'season': '2024/2025', 'team': 'Nottingham Forest', 'home_goals_season': 26, 'away_goals_season': 32, 'average_goals_season': 1.5263157894736843, 'first_half_season_goals_scored': 29, 'second_half_season_goals_scored': 29, 'average_season_first_half_goals_scored': 0.7631578947368421, 'average_season_second_half_goals_scored': 0.7631578947368421, 'first_half_home_season_goals_scored': 14, 'second_half_home_season_goals_scored': 12, 'average_home_game_first_half_goals_scored': 0.7368421052631579, 'average_home_game_second_half_goals_scored': 0.631578947368421, 'first_half_away_season_goals_scored': 15, 'second_half_away_season_goals_scored': 17, 'average_away_game_first_half_goals_scored': 0.7894736842105263, 'average_away_game_second_half_goals_scored': 0.8947368421052632}
{'season': '2024/2025', 'team': 'Southampton', 'home_goals_season': 13, 'away_goals_season': 13, 'average_goals_season': 0.6842105263157895, 'first_half_season_goals_scored': 12, 'second_half_season_goals_scored': 14, 'average_season_first_half_goals_scored': 0.3157894736842105, 'average_season_second_half_goals_scored': 0.3684210526315789, 'first_half_home_season_goals_scored': 8, 'second_half_home_season_goals_scored': 5, 'average_home_game_first_half_goals_scored': 0.42105263157894735, 'average_home_game_second_half_goals_scored': 0.2631578947368421, 'first_half_away_season_goals_scored': 4, 'second_half_away_season_goals_scored': 9, 'average_away_game_first_half_goals_scored': 0.21052631578947367, 'average_away_game_second_half_goals_scored': 0.47368421052631576}
{'season': '2024/2025', 'team': 'Tottenham', 'home_goals_season': 35, 'away_goals_season': 29, 'average_goals_season': 1.6842105263157894, 'first_half_season_goals_scored': 33, 'second_half_season_goals_scored': 31, 'average_season_first_half_goals_scored': 0.868421052631579, 'average_season_second_half_goals_scored': 0.8157894736842105, 'first_half_home_season_goals_scored': 16, 'second_half_home_season_goals_scored': 19, 'average_home_game_first_half_goals_scored': 0.8421052631578947, 'average_home_game_second_half_goals_scored': 1.0, 'first_half_away_season_goals_scored': 17, 'second_half_away_season_goals_scored': 12, 'average_away_game_first_half_goals_scored': 0.8947368421052632, 'average_away_game_second_half_goals_scored': 0.631578947368421}
{'season': '2024/2025', 'team': 'Wolves', 'home_goals_season': 27, 'away_goals_season': 27, 'average_goals_season': 1.4210526315789473, 'first_half_season_goals_scored': 26, 'second_half_season_goals_scored': 28, 'average_season_first_half_goals_scored': 0.6842105263157895, 'average_season_second_half_goals_scored': 0.7368421052631579, 'first_half_home_season_goals_scored': 13, 'second_half_home_season_goals_scored': 14, 'average_home_game_first_half_goals_scored': 0.6842105263157895, 'average_home_game_second_half_goals_scored': 0.7368421052631579, 'first_half_away_season_goals_scored': 13, 'second_half_away_season_goals_scored': 14, 'average_away_game_first_half_goals_scored': 0.6842105263157895, 'average_away_game_second_half_goals_scored': 0.7368421052631579}
{'season': '2024/2025', 'team': 'Crystal Palace', 'home_goals_season': 24, 'away_goals_season': 26, 'average_goals_season': 1.3157894736842106, 'first_half_season_goals_scored': 18, 'second_half_season_goals_scored': 32, 'average_season_first_half_goals_scored': 0.47368421052631576, 'average_season_second_half_goals_scored': 0.8421052631578947, 'first_half_home_season_goals_scored': 8, 'second_half_home_season_goals_scored': 16, 'average_home_game_first_half_goals_scored': 0.42105263157894735, 'average_home_game_second_half_goals_scored': 0.8421052631578947, 'first_half_away_season_goals_scored': 10, 'second_half_away_season_goals_scored': 16, 'average_away_game_first_half_goals_scored': 0.5263157894736842, 'average_away_game_second_half_goals_scored': 0.8421052631578947}
{'season': '2024/2025', 'team': 'Manchester City', 'home_goals_season': 43, 'away_goals_season': 27, 'average_goals_season': 1.8421052631578947, 'first_half_season_goals_scored': 40, 'second_half_season_goals_scored': 30, 'average_season_first_half_goals_scored': 1.0526315789473684, 'average_season_second_half_goals_scored': 0.7894736842105263, 'first_half_home_season_goals_scored': 28, 'second_half_home_season_goals_scored': 15, 'average_home_game_first_half_goals_scored': 1.4736842105263157, 'average_home_game_second_half_goals_scored': 0.7894736842105263, 'first_half_away_season_goals_scored': 12, 'second_half_away_season_goals_scored': 15, 'average_away_game_first_half_goals_scored': 0.631578947368421, 'average_away_game_second_half_goals_scored': 0.7894736842105263}
{'season': '2024/2025', 'team': 'Brighton', 'home_goals_season': 30, 'away_goals_season': 36, 'average_goals_season': 1.736842105263158, 'first_half_season_goals_scored': 27, 'second_half_season_goals_scored': 39, 'average_season_first_half_goals_scored': 0.7105263157894737, 'average_season_second_half_goals_scored': 1.0263157894736843, 'first_half_home_season_goals_scored': 13, 'second_half_home_season_goals_scored': 17, 'average_home_game_first_half_goals_scored': 0.6842105263157895, 'average_home_game_second_half_goals_scored': 0.8947368421052632, 'first_half_away_season_goals_scored': 14, 'second_half_away_season_goals_scored': 22, 'average_away_game_first_half_goals_scored': 0.7368421052631579, 'average_away_game_second_half_goals_scored': 1.1578947368421053}
{'season': '2024/2025', 'team': 'Arsenal', 'home_goals_season': 35, 'away_goals_season': 34, 'average_goals_season': 1.8157894736842106, 'first_half_season_goals_scored': 33, 'second_half_season_goals_scored': 36, 'average_season_first_half_goals_scored': 0.868421052631579, 'average_season_second_half_goals_scored': 0.9473684210526315, 'first_half_home_season_goals_scored': 17, 'second_half_home_season_goals_scored': 18, 'average_home_game_first_half_goals_scored': 0.8947368421052632, 'average_home_game_second_half_goals_scored': 0.9473684210526315, 'first_half_away_season_goals_scored': 16, 'second_half_away_season_goals_scored': 18, 'average_away_game_first_half_goals_scored': 0.8421052631578947, 'average_away_game_second_half_goals_scored': 0.9473684210526315}
{'season': '2024/2025', 'team': 'Brentford', 'home_goals_season': 40, 'away_goals_season': 26, 'average_goals_season': 1.736842105263158, 'first_half_season_goals_scored': 35, 'second_half_season_goals_scored': 31, 'average_season_first_half_goals_scored': 0.9210526315789473, 'average_season_second_half_goals_scored': 0.8157894736842105, 'first_half_home_season_goals_scored': 22, 'second_half_home_season_goals_scored': 18, 'average_home_game_first_half_goals_scored': 1.1578947368421053, 'average_home_game_second_half_goals_scored': 0.9473684210526315, 'first_half_away_season_goals_scored': 13, 'second_half_away_season_goals_scored': 13, 'average_away_game_first_half_goals_scored': 0.6842105263157895, 'average_away_game_second_half_goals_scored': 0.6842105263157895}
{'season': '2024/2025', 'team': 'Leicester', 'home_goals_season': 15, 'away_goals_season': 18, 'average_goals_season': 0.868421052631579, 'first_half_season_goals_scored': 12, 'second_half_season_goals_scored': 21, 'average_season_first_half_goals_scored': 0.3157894736842105, 'average_season_second_half_goals_scored': 0.5526315789473685, 'first_half_home_season_goals_scored': 6, 'second_half_home_season_goals_scored': 9, 'average_home_game_first_half_goals_scored': 0.3157894736842105, 'average_home_game_second_half_goals_scored': 0.47368421052631576, 'first_half_away_season_goals_scored': 6, 'second_half_away_season_goals_scored': 12, 'average_away_game_first_half_goals_scored': 0.3157894736842105, 'average_away_game_second_half_goals_scored': 0.631578947368421}
{'season': '2024/2025', 'team': 'West Ham', 'home_goals_season': 23, 'away_goals_season': 20, 'average_goals_season': 1.131578947368421, 'first_half_season_goals_scored': 16, 'second_half_season_goals_scored': 27, 'average_season_first_half_goals_scored': 0.42105263157894735, 'average_season_second_half_goals_scored': 0.7105263157894737, 'first_half_home_season_goals_scored': 11, 'second_half_home_season_goals_scored': 12, 'average_home_game_first_half_goals_scored': 0.5789473684210527, 'average_home_game_second_half_goals_scored': 0.631578947368421, 'first_half_away_season_goals_scored': 5, 'second_half_away_season_goals_scored': 15, 'average_away_game_first_half_goals_scored': 0.2631578947368421, 'average_away_game_second_half_goals_scored': 0.7894736842105263}
{'season': '2024/2025', 'team': 'Everton', 'home_goals_season': 26, 'away_goals_season': 15, 'average_goals_season': 1.0789473684210527, 'first_half_season_goals_scored': 25, 'second_half_season_goals_scored': 16, 'average_season_first_half_goals_scored': 0.6578947368421053, 'average_season_second_half_goals_scored': 0.42105263157894735, 'first_half_home_season_goals_scored': 15, 'second_half_home_season_goals_scored': 11, 'average_home_game_first_half_goals_scored': 0.7894736842105263, 'average_home_game_second_half_goals_scored': 0.5789473684210527, 'first_half_away_season_goals_scored': 10, 'second_half_away_season_goals_scored': 5, 'average_away_game_first_half_goals_scored': 0.5263157894736842, 'average_away_game_second_half_goals_scored': 0.2631578947368421}
{'season': '2024/2025', 'team': 'Chelsea', 'home_goals_season': 35, 'away_goals_season': 29, 'average_goals_season': 1.6842105263157894, 'first_half_season_goals_scored': 29, 'second_half_season_goals_scored': 35, 'average_season_first_half_goals_scored': 0.7631578947368421, 'average_season_second_half_goals_scored': 0.9210526315789473, 'first_half_home_season_goals_scored': 17, 'second_half_home_season_goals_scored': 18, 'average_home_game_first_half_goals_scored': 0.8947368421052632, 'average_home_game_second_half_goals_scored': 0.9473684210526315, 'first_half_away_season_goals_scored': 12, 'second_half_away_season_goals_scored': 17, 'average_away_game_first_half_goals_scored': 0.631578947368421, 'average_away_game_second_half_goals_scored': 0.8947368421052632}
{'season': '2024/2025', 'team': 'Aston Villa', 'home_goals_season': 34, 'away_goals_season': 24, 'average_goals_season': 1.5263157894736843, 'first_half_season_goals_scored': 23, 'second_half_season_goals_scored': 35, 'average_season_first_half_goals_scored': 0.6052631578947368, 'average_season_second_half_goals_scored': 0.9210526315789473, 'first_half_home_season_goals_scored': 15, 'second_half_home_season_goals_scored': 19, 'average_home_game_first_half_goals_scored': 0.7894736842105263, 'average_home_game_second_half_goals_scored': 1.0, 'first_half_away_season_goals_scored': 8, 'second_half_away_season_goals_scored': 16, 'average_away_game_first_half_goals_scored': 0.42105263157894735, 'average_away_game_second_half_goals_scored': 0.8421052631578947}
{'season': '2024/2025', 'team': 'Liverpool', 'home_goals_season': 41, 'away_goals_season': 44, 'average_goals_season': 2.236842105263158, 'first_half_season_goals_scored': 40, 'second_half_season_goals_scored': 45, 'average_season_first_half_goals_scored': 1.0526315789473684, 'average_season_second_half_goals_scored': 1.1842105263157894, 'first_half_home_season_goals_scored': 20, 'second_half_home_season_goals_scored': 21, 'average_home_game_first_half_goals_scored': 1.0526315789473684, 'average_home_game_second_half_goals_scored': 1.105263157894737, 'first_half_away_season_goals_scored': 20, 'second_half_away_season_goals_scored': 24, 'average_away_game_first_half_goals_scored': 1.0526315789473684, 'average_away_game_second_half_goals_scored': 1.263157894736842}
{'season': '2024/2025', 'team': 'Manchester Utd', 'home_goals_season': 21, 'away_goals_season': 21, 'average_goals_season': 1.105263157894737, 'first_half_season_goals_scored': 15, 'second_half_season_goals_scored': 27, 'average_season_first_half_goals_scored': 0.39473684210526316, 'average_season_second_half_goals_scored': 0.7105263157894737, 'first_half_home_season_goals_scored': 9, 'second_half_home_season_goals_scored': 12, 'average_home_game_first_half_goals_scored': 0.47368421052631576, 'average_home_game_second_half_goals_scored': 0.631578947368421, 'first_half_away_season_goals_scored': 6, 'second_half_away_season_goals_scored': 15, 'average_away_game_first_half_goals_scored': 0.3157894736842105, 'average_away_game_second_half_goals_scored': 0.7894736842105263}
{'season': '2024/2025', 'team': 'Newcastle', 'home_goals_season': 40, 'away_goals_season': 28, 'average_goals_season': 1.7894736842105263, 'first_half_season_goals_scored': 37, 'second_half_season_goals_scored': 31, 'average_season_first_half_goals_scored': 0.9736842105263158, 'average_season_second_half_goals_scored': 0.8157894736842105, 'first_half_home_season_goals_scored': 21, 'second_half_home_season_goals_scored': 19, 'average_home_game_first_half_goals_scored': 1.105263157894737, 'average_home_game_second_half_goals_scored': 1.0, 'first_half_away_season_goals_scored': 16, 'second_half_away_season_goals_scored': 12, 'average_away_game_first_half_goals_scored': 0.8421052631578947, 'average_away_game_second_half_goals_scored': 0.631578947368421}
{'season': '2024/2025', 'team': 'Bournemouth', 'home_goals_season': 21, 'away_goals_season': 35, 'average_goals_season': 1.4736842105263157, 'first_half_season_goals_scored': 21, 'second_half_season_goals_scored': 35, 'average_season_first_half_goals_scored': 0.5526315789473685, 'average_season_second_half_goals_scored': 0.9210526315789473, 'first_half_home_season_goals_scored': 10, 'second_half_home_season_goals_scored': 11, 'average_home_game_first_half_goals_scored': 0.5263157894736842, 'average_home_game_second_half_goals_scored': 0.5789473684210527, 'first_half_away_season_goals_scored': 11, 'second_half_away_season_goals_scored': 24, 'average_away_game_first_half_goals_scored': 0.5789473684210527, 'average_away_game_second_half_goals_scored': 1.263157894736842}
{'season': '2024/2025', 'team': 'Fulham', 'home_goals_season': 27, 'away_goals_season': 27, 'average_goals_season': 1.4210526315789473, 'first_half_season_goals_scored': 22, 'second_half_season_goals_scored': 32, 'average_season_first_half_goals_scored': 0.5789473684210527, 'average_season_second_half_goals_scored': 0.8421052631578947, 'first_half_home_season_goals_scored': 15, 'second_half_home_season_goals_scored': 12, 'average_home_game_first_half_goals_scored': 0.7894736842105263, 'average_home_game_second_half_goals_scored': 0.631578947368421, 'first_half_away_season_goals_scored': 7, 'second_half_away_season_goals_scored': 20, 'average_away_game_first_half_goals_scored': 0.3684210526315789, 'average_away_game_second_half_goals_scored': 1.0526315789473684}

KeyboardInterrupt:

In [27]:
individual_season

'2024/2025'

In [ ]:
print(len(df2[(df2['home_team'] == 'Fulham') & (df2['event_type'] == 'goal') & (df2['team_side'] == 'home') & (df2['season'] == individual_season)]))
print(len(df2[(df2['away_team'] == 'Fulham') & (df2['event_type'] == 'goal') & (df2['team_side'] == 'away') & (df2['season'] == individual_season)]))

28
24

In [36]:
len(df2[(df2['home_team'] == 'Fulham') & (df2['event_type'] == 'goal') & (df2['team_side'] == 'away') & (df2['season'] == individual_season)])

28

In [39]:
len(df2[(df2['away_team'] == 'Fulham') & (df2['event_type'] == 'goal') & (df2['team_side'] == 'home') & (df2['season'] == individual_season)])

24

In [41]:
goals_stats_teams

[{'season': '2024/2025',
  'team': 'Nottingham Forest',
  'home_goals_season': 26,
  'away_goals_season': 32,
  'average_goals_season': 1.5263157894736843,
  'first_half_season_goals_scored': 29,
  'second_half_season_goals_scored': 29,
  'average_season_first_half_goals_scored': 0.7631578947368421,
  'average_season_second_half_goals_scored': 0.7631578947368421,
  'first_half_home_season_goals_scored': 14,
  'second_half_home_season_goals_scored': 12,
  'average_home_game_first_half_goals_scored': 0.7368421052631579,
  'average_home_game_second_half_goals_scored': 0.631578947368421,
  'first_half_away_season_goals_scored': 15,
  'second_half_away_season_goals_scored': 17,
  'average_away_game_first_half_goals_scored': 0.7894736842105263,
  'average_away_game_second_half_goals_scored': 0.8947368421052632},
 {'season': '2024/2025',
  'team': 'Southampton',
  'home_goals_season': 13,
  'away_goals_season': 13,
  'average_goals_season': 0.6842105263157895,
  'first_half_season_goals_scored': 12,
  'second_half_season_goals_scored': 14,
  'average_season_first_half_goals_scored': 0.3157894736842105,
  'average_season_second_half_goals_scored': 0.3684210526315789,
  'first_half_home_season_goals_scored': 8,
  'second_half_home_season_goals_scored': 5,
  'average_home_game_first_half_goals_scored': 0.42105263157894735,
  'average_home_game_second_half_goals_scored': 0.2631578947368421,
  'first_half_away_season_goals_scored': 4,
  'second_half_away_season_goals_scored': 9,
  'average_away_game_first_half_goals_scored': 0.21052631578947367,
  'average_away_game_second_half_goals_scored': 0.47368421052631576},
 {'season': '2024/2025',
  'team': 'Tottenham',
  'home_goals_season': 35,
  'away_goals_season': 29,
  'average_goals_season': 1.6842105263157894,
  'first_half_season_goals_scored': 33,
  'second_half_season_goals_scored': 31,
  'average_season_first_half_goals_scored': 0.868421052631579,
  'average_season_second_half_goals_scored': 0.8157894736842105,
  'first_half_home_season_goals_scored': 16,
  'second_half_home_season_goals_scored': 19,
  'average_home_game_first_half_goals_scored': 0.8421052631578947,
  'average_home_game_second_half_goals_scored': 1.0,
  'first_half_away_season_goals_scored': 17,
  'second_half_away_season_goals_scored': 12,
  'average_away_game_first_half_goals_scored': 0.8947368421052632,
  'average_away_game_second_half_goals_scored': 0.631578947368421},
 {'season': '2024/2025',
  'team': 'Wolves',
  'home_goals_season': 27,
  'away_goals_season': 27,
  'average_goals_season': 1.4210526315789473,
  'first_half_season_goals_scored': 26,
  'second_half_season_goals_scored': 28,
  'average_season_first_half_goals_scored': 0.6842105263157895,
  'average_season_second_half_goals_scored': 0.7368421052631579,
  'first_half_home_season_goals_scored': 13,
  'second_half_home_season_goals_scored': 14,
  'average_home_game_first_half_goals_scored': 0.6842105263157895,
  'average_home_game_second_half_goals_scored': 0.7368421052631579,
  'first_half_away_season_goals_scored': 13,
  'second_half_away_season_goals_scored': 14,
  'average_away_game_first_half_goals_scored': 0.6842105263157895,
  'average_away_game_second_half_goals_scored': 0.7368421052631579},
 {'season': '2024/2025',
  'team': 'Crystal Palace',
  'home_goals_season': 24,
  'away_goals_season': 26,
  'average_goals_season': 1.3157894736842106,
  'first_half_season_goals_scored': 18,
  'second_half_season_goals_scored': 32,
  'average_season_first_half_goals_scored': 0.47368421052631576,
  'average_season_second_half_goals_scored': 0.8421052631578947,
  'first_half_home_season_goals_scored': 8,
  'second_half_home_season_goals_scored': 16,
  'average_home_game_first_half_goals_scored': 0.42105263157894735,
  'average_home_game_second_half_goals_scored': 0.8421052631578947,
  'first_half_away_season_goals_scored': 10,
  'second_half_away_season_goals_scored': 16,
  'average_away_game_first_half_goals_scored': 0.5263157894736842,
  'average_away_game_second_half_goals_scored': 0.8421052631578947},
 {'season': '2024/2025',
  'team': 'Manchester City',
  'home_goals_season': 43,
  'away_goals_season': 27,
  'average_goals_season': 1.8421052631578947,
  'first_half_season_goals_scored': 40,
  'second_half_season_goals_scored': 30,
  'average_season_first_half_goals_scored': 1.0526315789473684,
  'average_season_second_half_goals_scored': 0.7894736842105263,
  'first_half_home_season_goals_scored': 28,
  'second_half_home_season_goals_scored': 15,
  'average_home_game_first_half_goals_scored': 1.4736842105263157,
  'average_home_game_second_half_goals_scored': 0.7894736842105263,
  'first_half_away_season_goals_scored': 12,
  'second_half_away_season_goals_scored': 15,
  'average_away_game_first_half_goals_scored': 0.631578947368421,
  'average_away_game_second_half_goals_scored': 0.7894736842105263},
 {'season': '2024/2025',
  'team': 'Brighton',
  'home_goals_season': 30,
  'away_goals_season': 36,
  'average_goals_season': 1.736842105263158,
  'first_half_season_goals_scored': 27,
  'second_half_season_goals_scored': 39,
  'average_season_first_half_goals_scored': 0.7105263157894737,
  'average_season_second_half_goals_scored': 1.0263157894736843,
  'first_half_home_season_goals_scored': 13,
  'second_half_home_season_goals_scored': 17,
  'average_home_game_first_half_goals_scored': 0.6842105263157895,
  'average_home_game_second_half_goals_scored': 0.8947368421052632,
  'first_half_away_season_goals_scored': 14,
  'second_half_away_season_goals_scored': 22,
  'average_away_game_first_half_goals_scored': 0.7368421052631579,
  'average_away_game_second_half_goals_scored': 1.1578947368421053},
 {'season': '2024/2025',
  'team': 'Arsenal',
  'home_goals_season': 35,
  'away_goals_season': 34,
  'average_goals_season': 1.8157894736842106,
  'first_half_season_goals_scored': 33,
  'second_half_season_goals_scored': 36,
  'average_season_first_half_goals_scored': 0.868421052631579,
  'average_season_second_half_goals_scored': 0.9473684210526315,
  'first_half_home_season_goals_scored': 17,
  'second_half_home_season_goals_scored': 18,
  'average_home_game_first_half_goals_scored': 0.8947368421052632,
  'average_home_game_second_half_goals_scored': 0.9473684210526315,
  'first_half_away_season_goals_scored': 16,
  'second_half_away_season_goals_scored': 18,
  'average_away_game_first_half_goals_scored': 0.8421052631578947,
  'average_away_game_second_half_goals_scored': 0.9473684210526315},
 {'season': '2024/2025',
  'team': 'Brentford',
  'home_goals_season': 40,
  'away_goals_season': 26,
  'average_goals_season': 1.736842105263158,
  'first_half_season_goals_scored': 35,
  'second_half_season_goals_scored': 31,
  'average_season_first_half_goals_scored': 0.9210526315789473,
  'average_season_second_half_goals_scored': 0.8157894736842105,
  'first_half_home_season_goals_scored': 22,
  'second_half_home_season_goals_scored': 18,
  'average_home_game_first_half_goals_scored': 1.1578947368421053,
  'average_home_game_second_half_goals_scored': 0.9473684210526315,
  'first_half_away_season_goals_scored': 13,
  'second_half_away_season_goals_scored': 13,
  'average_away_game_first_half_goals_scored': 0.6842105263157895,
  'average_away_game_second_half_goals_scored': 0.6842105263157895},
 {'season': '2024/2025',
  'team': 'Leicester',
  'home_goals_season': 15,
  'away_goals_season': 18,
  'average_goals_season': 0.868421052631579,
  'first_half_season_goals_scored': 12,
  'second_half_season_goals_scored': 21,
  'average_season_first_half_goals_scored': 0.3157894736842105,
  'average_season_second_half_goals_scored': 0.5526315789473685,
  'first_half_home_season_goals_scored': 6,
  'second_half_home_season_goals_scored': 9,
  'average_home_game_first_half_goals_scored': 0.3157894736842105,
  'average_home_game_second_half_goals_scored': 0.47368421052631576,
  'first_half_away_season_goals_scored': 6,
  'second_half_away_season_goals_scored': 12,
  'average_away_game_first_half_goals_scored': 0.3157894736842105,
  'average_away_game_second_half_goals_scored': 0.631578947368421},
 {'season': '2024/2025',
  'team': 'West Ham',
  'home_goals_season': 23,
  'away_goals_season': 20,
  'average_goals_season': 1.131578947368421,
  'first_half_season_goals_scored': 16,
  'second_half_season_goals_scored': 27,
  'average_season_first_half_goals_scored': 0.42105263157894735,
  'average_season_second_half_goals_scored': 0.7105263157894737,
  'first_half_home_season_goals_scored': 11,
  'second_half_home_season_goals_scored': 12,
  'average_home_game_first_half_goals_scored': 0.5789473684210527,
  'average_home_game_second_half_goals_scored': 0.631578947368421,
  'first_half_away_season_goals_scored': 5,
  'second_half_away_season_goals_scored': 15,
  'average_away_game_first_half_goals_scored': 0.2631578947368421,
  'average_away_game_second_half_goals_scored': 0.7894736842105263},
 {'season': '2024/2025',
  'team': 'Everton',
  'home_goals_season': 26,
  'away_goals_season': 15,
  'average_goals_season': 1.0789473684210527,
  'first_half_season_goals_scored': 25,
  'second_half_season_goals_scored': 16,
  'average_season_first_half_goals_scored': 0.6578947368421053,
  'average_season_second_half_goals_scored': 0.42105263157894735,
  'first_half_home_season_goals_scored': 15,
  'second_half_home_season_goals_scored': 11,
  'average_home_game_first_half_goals_scored': 0.7894736842105263,
  'average_home_game_second_half_goals_scored': 0.5789473684210527,
  'first_half_away_season_goals_scored': 10,
  'second_half_away_season_goals_scored': 5,
  'average_away_game_first_half_goals_scored': 0.5263157894736842,
  'average_away_game_second_half_goals_scored': 0.2631578947368421},
 {'season': '2024/2025',
  'team': 'Chelsea',
  'home_goals_season': 35,
  'away_goals_season': 29,
  'average_goals_season': 1.6842105263157894,
  'first_half_season_goals_scored': 29,
  'second_half_season_goals_scored': 35,
  'average_season_first_half_goals_scored': 0.7631578947368421,
  'average_season_second_half_goals_scored': 0.9210526315789473,
  'first_half_home_season_goals_scored': 17,
  'second_half_home_season_goals_scored': 18,
  'average_home_game_first_half_goals_scored': 0.8947368421052632,
  'average_home_game_second_half_goals_scored': 0.9473684210526315,
  'first_half_away_season_goals_scored': 12,
  'second_half_away_season_goals_scored': 17,
  'average_away_game_first_half_goals_scored': 0.631578947368421,
  'average_away_game_second_half_goals_scored': 0.8947368421052632},
 {'season': '2024/2025',
  'team': 'Aston Villa',
  'home_goals_season': 34,
  'away_goals_season': 24,
  'average_goals_season': 1.5263157894736843,
  'first_half_season_goals_scored': 23,
  'second_half_season_goals_scored': 35,
  'average_season_first_half_goals_scored': 0.6052631578947368,
  'average_season_second_half_goals_scored': 0.9210526315789473,
  'first_half_home_season_goals_scored': 15,
  'second_half_home_season_goals_scored': 19,
  'average_home_game_first_half_goals_scored': 0.7894736842105263,
  'average_home_game_second_half_goals_scored': 1.0,
  'first_half_away_season_goals_scored': 8,
  'second_half_away_season_goals_scored': 16,
  'average_away_game_first_half_goals_scored': 0.42105263157894735,
  'average_away_game_second_half_goals_scored': 0.8421052631578947},
 {'season': '2024/2025',
  'team': 'Liverpool',
  'home_goals_season': 41,
  'away_goals_season': 44,
  'average_goals_season': 2.236842105263158,
  'first_half_season_goals_scored': 40,
  'second_half_season_goals_scored': 45,
  'average_season_first_half_goals_scored': 1.0526315789473684,
  'average_season_second_half_goals_scored': 1.1842105263157894,
  'first_half_home_season_goals_scored': 20,
  'second_half_home_season_goals_scored': 21,
  'average_home_game_first_half_goals_scored': 1.0526315789473684,
  'average_home_game_second_half_goals_scored': 1.105263157894737,
  'first_half_away_season_goals_scored': 20,
  'second_half_away_season_goals_scored': 24,
  'average_away_game_first_half_goals_scored': 1.0526315789473684,
  'average_away_game_second_half_goals_scored': 1.263157894736842},
 {'season': '2024/2025',
  'team': 'Manchester Utd',
  'home_goals_season': 21,
  'away_goals_season': 21,
  'average_goals_season': 1.105263157894737,
  'first_half_season_goals_scored': 15,
  'second_half_season_goals_scored': 27,
  'average_season_first_half_goals_scored': 0.39473684210526316,
  'average_season_second_half_goals_scored': 0.7105263157894737,
  'first_half_home_season_goals_scored': 9,
  'second_half_home_season_goals_scored': 12,
  'average_home_game_first_half_goals_scored': 0.47368421052631576,
  'average_home_game_second_half_goals_scored': 0.631578947368421,
  'first_half_away_season_goals_scored': 6,
  'second_half_away_season_goals_scored': 15,
  'average_away_game_first_half_goals_scored': 0.3157894736842105,
  'average_away_game_second_half_goals_scored': 0.7894736842105263},
 {'season': '2024/2025',
  'team': 'Newcastle',
  'home_goals_season': 40,
  'away_goals_season': 28,
  'average_goals_season': 1.7894736842105263,
  'first_half_season_goals_scored': 37,
  'second_half_season_goals_scored': 31,
  'average_season_first_half_goals_scored': 0.9736842105263158,
  'average_season_second_half_goals_scored': 0.8157894736842105,
  'first_half_home_season_goals_scored': 21,
  'second_half_home_season_goals_scored': 19,
  'average_home_game_first_half_goals_scored': 1.105263157894737,
  'average_home_game_second_half_goals_scored': 1.0,
  'first_half_away_season_goals_scored': 16,
  'second_half_away_season_goals_scored': 12,
  'average_away_game_first_half_goals_scored': 0.8421052631578947,
  'average_away_game_second_half_goals_scored': 0.631578947368421},
 {'season': '2024/2025',
  'team': 'Bournemouth',
  'home_goals_season': 21,
  'away_goals_season': 35,
  'average_goals_season': 1.4736842105263157,
  'first_half_season_goals_scored': 21,
  'second_half_season_goals_scored': 35,
  'average_season_first_half_goals_scored': 0.5526315789473685,
  'average_season_second_half_goals_scored': 0.9210526315789473,
  'first_half_home_season_goals_scored': 10,
  'second_half_home_season_goals_scored': 11,
  'average_home_game_first_half_goals_scored': 0.5263157894736842,
  'average_home_game_second_half_goals_scored': 0.5789473684210527,
  'first_half_away_season_goals_scored': 11,
  'second_half_away_season_goals_scored': 24,
  'average_away_game_first_half_goals_scored': 0.5789473684210527,
  'average_away_game_second_half_goals_scored': 1.263157894736842},
 {'season': '2024/2025',
  'team': 'Fulham',
  'home_goals_season': 27,
  'away_goals_season': 27,
  'average_goals_season': 1.4210526315789473,
  'first_half_season_goals_scored': 22,
  'second_half_season_goals_scored': 32,
  'average_season_first_half_goals_scored': 0.5789473684210527,
  'average_season_second_half_goals_scored': 0.8421052631578947,
  'first_half_home_season_goals_scored': 15,
  'second_half_home_season_goals_scored': 12,
  'average_home_game_first_half_goals_scored': 0.7894736842105263,
  'average_home_game_second_half_goals_scored': 0.631578947368421,
  'first_half_away_season_goals_scored': 7,
  'second_half_away_season_goals_scored': 20,
  'average_away_game_first_half_goals_scored': 0.3684210526315789,
  'average_away_game_second_half_goals_scored': 1.0526315789473684}]

In [ ]:
df['home_team']

,match_id,competition,datetime,season,home_team,away_team,team_side,event_source,event_type,time,player,score,assist,player_in,player_out,reason
0,0,PREMIER LEAGUE - JORNADA 38,25.05.2025 10:00,2024/2025,Nottingham Forest,Chelsea,home,list_0,yellow_card,32',Anderson E.,None,None,None,None,(Derribar a un rival)
1,0,PREMIER LEAGUE - JORNADA 38,25.05.2025 10:00,2024/2025,Nottingham Forest,Chelsea,home,list_0,substitution,57',Hudson-Odoi C.,None,None,Hudson-Odoi C.,Sangaré I.,None
2,0,PREMIER LEAGUE - JORNADA 38,25.05.2025 10:00,2024/2025,Nottingham Forest,Chelsea,home,list_0,substitution,68',Yates R.,None,None,Yates R.,Dominguez N.,None
3,0,PREMIER LEAGUE - JORNADA 38,25.05.2025 10:00,2024/2025,Nottingham Forest,Chelsea,home,list_0,yellow_card,79',Aina O.,None,None,None,None,(Falta)
4,0,PREMIER LEAGUE - JORNADA 38,25.05.2025 10:00,2024/2025,Nottingham Forest,Chelsea,home,list_0,substitution,83',Jota Silva,None,None,Jota Silva,Aina O.,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85564,7027,PREMIER LEAGUE - JORNADA 1,19.08.2006 06:45,2006/2007,Sheffield Utd,Liverpool,away,list_1,substitution,34',Agger D.,None,None,Agger D.,Carragher J.,None
85565,7027,PREMIER LEAGUE - JORNADA 1,19.08.2006 06:45,2006/2007,Sheffield Utd,Liverpool,away,list_1,yellow_card,64',Sissoko M.,None,None,None,None,None
85566,7027,PREMIER LEAGUE - JORNADA 1,19.08.2006 06:45,2006/2007,Sheffield Utd,Liverpool,away,list_1,goal,70',Fowler R.,1 - 1,None,None,None,None
85567,7027,PREMIER LEAGUE - JORNADA 1,19.08.2006 06:45,2006/2007,Sheffield Utd,Liverpool,away,list_1,yellow_card,82',Kromkamp J.,None,None,None,None,None
85568,7027,PREMIER LEAGUE - JORNADA 1,19.08.2006 06:45,2006/2007,Sheffield Utd,Liverpool,away,list_1,substitution,83',Pennant J.,None,None,Pennant J.,Fowler R.,None

In [51]:
df2

,match_id,competition,datetime,season,home_team,away_team,team_side,event_source,event_type,time,player,score,assist,player_in,player_out,reason,matchweek,half_event
0,0,PREMIER LEAGUE,25.05.2025 10:00,2024/2025,Nottingham Forest,Chelsea,home,list_0,yellow_card,32',Anderson E.,None,None,None,None,(Derribar a un rival),JORNADA 38,First Half
1,0,PREMIER LEAGUE,25.05.2025 10:00,2024/2025,Nottingham Forest,Chelsea,home,list_0,substitution,57',Hudson-Odoi C.,None,None,Hudson-Odoi C.,Sangaré I.,None,JORNADA 38,Second Half
2,0,PREMIER LEAGUE,25.05.2025 10:00,2024/2025,Nottingham Forest,Chelsea,home,list_0,substitution,68',Yates R.,None,None,Yates R.,Dominguez N.,None,JORNADA 38,Second Half
3,0,PREMIER LEAGUE,25.05.2025 10:00,2024/2025,Nottingham Forest,Chelsea,home,list_0,yellow_card,79',Aina O.,None,None,None,None,(Falta),JORNADA 38,Second Half
4,0,PREMIER LEAGUE,25.05.2025 10:00,2024/2025,Nottingham Forest,Chelsea,home,list_0,substitution,83',Jota Silva,None,None,Jota Silva,Aina O.,None,JORNADA 38,Second Half
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85564,7027,PREMIER LEAGUE,19.08.2006 06:45,2006/2007,Sheffield Utd,Liverpool,away,list_1,substitution,34',Agger D.,None,None,Agger D.,Carragher J.,None,JORNADA 1,First Half
85565,7027,PREMIER LEAGUE,19.08.2006 06:45,2006/2007,Sheffield Utd,Liverpool,away,list_1,yellow_card,64',Sissoko M.,None,None,None,None,None,JORNADA 1,Second Half
85566,7027,PREMIER LEAGUE,19.08.2006 06:45,2006/2007,Sheffield Utd,Liverpool,away,list_1,goal,70',Fowler R.,1 - 1,None,None,None,None,JORNADA 1,Second Half
85567,7027,PREMIER LEAGUE,19.08.2006 06:45,2006/2007,Sheffield Utd,Liverpool,away,list_1,yellow_card,82',Kromkamp J.,None,None,None,None,None,JORNADA 1,Second Half
85568,7027,PREMIER LEAGUE,19.08.2006 06:45,2006/2007,Sheffield Utd,Liverpool,away,list_1,substitution,83',Pennant J.,None,None,Pennant J.,Fowler R.,None,JORNADA 1,Second Half

In [48]:
df2[(df2['home_team'] == 'Fulham') & (df2['event_type'] == 'goal') & (df2['season'] == individual_season)]

,match_id,competition,datetime,season,home_team,away_team,team_side,event_source,event_type,time,player,score,assist,player_in,player_out,reason,matchweek,half_event
320,20,PREMIER LEAGUE,10.05.2025 09:00,2024/2025,Fulham,Everton,home,list_0,goal,17',Jiménez R.,1 - 0,Smith Rowe E.,None,None,None,JORNADA 36,First Half
327,20,PREMIER LEAGUE,10.05.2025 09:00,2024/2025,Fulham,Everton,away,list_1,goal,45+3',Mykolenko V.,1 - 1,Doucouré A.,None,None,None,JORNADA 36,First Half
330,20,PREMIER LEAGUE,10.05.2025 09:00,2024/2025,Fulham,Everton,away,list_1,goal,70',Keane M.,1 - 2,McNeil D.,None,None,None,JORNADA 36,Second Half
331,20,PREMIER LEAGUE,10.05.2025 09:00,2024/2025,Fulham,Everton,away,list_1,goal,74',Beto,1 - 3,Alcaraz C.,None,None,None,JORNADA 36,Second Half
726,46,PREMIER LEAGUE,20.04.2025 08:00,2024/2025,Fulham,Chelsea,home,list_0,goal,20',Iwobi A.,1 - 0,Sessegnon R.,None,None,None,JORNADA 33,First Half
738,46,PREMIER LEAGUE,20.04.2025 08:00,2024/2025,Fulham,Chelsea,away,list_1,goal,83',George T.,1 - 1,None,None,None,None,JORNADA 33,Second Half
741,46,PREMIER LEAGUE,20.04.2025 08:00,2024/2025,Fulham,Chelsea,away,list_1,goal,90+3',Neto P.,1 - 2,Fernández E.,None,None,None,JORNADA 33,Second Half
1082,68,PREMIER LEAGUE,06.04.2025 08:00,2024/2025,Fulham,Liverpool,home,list_0,goal,23',Sessegnon R.,1 - 1,None,None,None,None,JORNADA 31,First Half
1083,68,PREMIER LEAGUE,06.04.2025 08:00,2024/2025,Fulham,Liverpool,home,list_0,goal,32',Iwobi A.,2 - 1,None,None,None,None,JORNADA 31,First Half
1084,68,PREMIER LEAGUE,06.04.2025 08:00,2024/2025,Fulham,Liverpool,home,list_0,goal,37',Rodrigo Muniz,3 - 1,Iwobi A.,None,None,None,JORNADA 31,First Half
1093,68,PREMIER LEAGUE,06.04.2025 08:00,2024/2025,Fulham,Liverpool,away,list_1,goal,14',Mac Allister A.,0 - 1,Gravenberch R.,None,None,None,JORNADA 31,First Half
1098,68,PREMIER LEAGUE,06.04.2025 08:00,2024/2025,Fulham,Liverpool,away,list_1,goal,72',Diaz L.,3 - 2,Bradley C.,None,None,None,JORNADA 31,Second Half
1392,87,PREMIER LEAGUE,16.03.2025 08:30,2024/2025,Fulham,Tottenham,home,list_0,goal,78',Rodrigo Muniz,1 - 0,Pereira A.,None,None,None,JORNADA 29,Second Half
1394,87,PREMIER LEAGUE,16.03.2025 08:30,2024/2025,Fulham,Tottenham,home,list_0,goal,88',Sessegnon R.,2 - 0,None,None,None,None,JORNADA 29,Second Half
1843,118,PREMIER LEAGUE,22.02.2025 10:00,2024/2025,Fulham,Crystal Palace,away,list_1,goal,37',Andersen J.,0 - 1,None,None,None,None,JORNADA 26,First Half
1846,118,PREMIER LEAGUE,22.02.2025 10:00,2024/2025,Fulham,Crystal Palace,away,list_1,goal,66',Muñoz D.,0 - 2,Mateta J.,None,None,None,JORNADA 26,Second Half
1990,128,PREMIER LEAGUE,15.02.2025 10:00,2024/2025,Fulham,Nottingham Forest,home,list_0,goal,15',Smith Rowe E.,1 - 0,Traoré A.,None,None,None,JORNADA 25,First Half
1991,128,PREMIER LEAGUE,15.02.2025 10:00,2024/2025,Fulham,Nottingham Forest,home,list_0,goal,62',Bassey C.,2 - 1,Jiménez R.,None,None,None,JORNADA 25,Second Half
1997,128,PREMIER LEAGUE,15.02.2025 10:00,2024/2025,Fulham,Nottingham Forest,away,list_1,goal,37',Wood Ch.,1 - 1,Gibbs-White M.,None,None,None,JORNADA 25,First Half
2259,145,PREMIER LEAGUE,26.01.2025 14:00,2024/2025,Fulham,Manchester Utd,away,list_1,goal,78',Martínez L.,0 - 1,None,None,None,None,JORNADA 23,Second Half
2745,177,PREMIER LEAGUE,05.01.2025 09:00,2024/2025,Fulham,Ipswich,home,list_0,goal,69',Jiménez R.,1 - 1,None,None,None,None,JORNADA 20,Second Half
2747,177,PREMIER LEAGUE,05.01.2025 09:00,2024/2025,Fulham,Ipswich,home,list_0,goal,90+1',Jiménez R.,2 - 2,None,None,None,None,JORNADA 20,Second Half
2750,177,PREMIER LEAGUE,05.01.2025 09:00,2024/2025,Fulham,Ipswich,away,list_1,goal,38',Szmodics S.,0 - 1,None,None,None,None,JORNADA 20,First Half
2754,177,PREMIER LEAGUE,05.01.2025 09:00,2024/2025,Fulham,Ipswich,away,list_1,goal,71',Delap L.,1 - 2,None,None,None,None,JORNADA 20,Second Half
2968,192,PREMIER LEAGUE,29.12.2024 10:00,2024/2025,Fulham,Bournemouth,home,list_0,goal,40',Jiménez R.,1 - 0,Pereira A.,None,None,None,JORNADA 19,First Half
2971,192,PREMIER LEAGUE,29.12.2024 10:00,2024/2025,Fulham,Bournemouth,home,list_0,goal,72',Wilson H.,2 - 1,Robinson A.,None,None,None,JORNADA 19,Second Half
2978,192,PREMIER LEAGUE,29.12.2024 10:00,2024/2025,Fulham,Bournemouth,away,list_1,goal,51',Evanilson,1 - 1,Hill J.,None,None,None,JORNADA 19,Second Half
2984,192,PREMIER LEAGUE,29.12.2024 10:00,2024/2025,Fulham,Bournemouth,away,list_1,goal,89',Ouattara Da.,2 - 2,Semenyo A.,None,None,None,JORNADA 19,Second Half
3517,227,PREMIER LEAGUE,08.12.2024 09:00,2024/2025,Fulham,Arsenal,home,list_0,goal,11',Jiménez R.,1 - 0,Tete K.,None,None,None,JORNADA 15,First Half
3526,227,PREMIER LEAGUE,08.12.2024 09:00,2024/2025,Fulham,Arsenal,away,list_1,goal,52',Saliba W.,1 - 1,Havertz K.,None,None,None,JORNADA 15,Second Half
3640,235,PREMIER LEAGUE,05.12.2024 14:30,2024/2025,Fulham,Brighton,home,list_0,goal,4',Iwobi A.,1 - 0,None,None,None,None,JORNADA 14,First Half
3644,235,PREMIER LEAGUE,05.12.2024 14:30,2024/2025,Fulham,Brighton,home,list_0,goal,79',O'Riley M.,2 - 1,None,None,None,None,JORNADA 14,Second Half
3647,235,PREMIER LEAGUE,05.12.2024 14:30,2024/2025,Fulham,Brighton,home,list_0,goal,87',Iwobi A.,3 - 1,Robinson A.,None,None,None,JORNADA 14,Second Half
3650,235,PREMIER LEAGUE,05.12.2024 14:30,2024/2025,Fulham,Brighton,away,list_1,goal,56',Baleba C.,1 - 1,Joao Pedro,None,None,None,JORNADA 14,Second Half
4089,262,PREMIER LEAGUE,23.11.2024 10:00,2024/2025,Fulham,Wolves,home,list_0,goal,20',Iwobi A.,1 - 0,Tete K.,None,None,None,JORNADA 12,First Half
4098,262,PREMIER LEAGUE,23.11.2024 10:00,2024/2025,Fulham,Wolves,away,list_1,goal,31',Cunha M.,1 - 1,Lemina M.,None,None,None,JORNADA 12,First Half
4099,262,PREMIER LEAGUE,23.11.2024 10:00,2024/2025,Fulham,Wolves,away,list_1,goal,53',Joao Gomes,1 - 2,Cunha M.,None,None,None,JORNADA 12,Second Half
4101,262,PREMIER LEAGUE,23.11.2024 10:00,2024/2025,Fulham,Wolves,away,list_1,goal,87',Cunha M.,1 - 3,Joao Gomes,None,None,None,JORNADA 12,Second Half
4105,262,PREMIER LEAGUE,23.11.2024 10:00,2024/2025,Fulham,Wolves,away,list_1,goal,90+5',Guedes G.,1 - 4,Larsen J. S.,None,None,None,JORNADA 12,Second Half
4283,274,PREMIER LEAGUE,04.11.2024 15:00,2024/2025,Fulham,Brentford,home,list_0,goal,90+2',Wilson H.,1 - 1,Traoré A.,None,None,None,JORNADA 10,Second Half
4284,274,PREMIER LEAGUE,04.11.2024 15:00,2024/2025,Fulham,Brentford,home,list_0,goal,90+7',Wilson H.,2 - 1,Robinson A.,None,None,None,JORNADA 10,Second Half
4287,274,PREMIER LEAGUE,04.11.2024 15:00,2024/2025,Fulham,Brentford,away,list_1,goal,24',Janelt V.,0 - 1,Norgaard C.,None,None,None,JORNADA 10,First Half
4685,298,PREMIER LEAGUE,19.10.2024 09:00,2024/2025,Fulham,Aston Villa,home,list_0,goal,5',Jiménez R.,1 - 0,Leno B.,None,None,None,JORNADA 8,First Half
4695,298,PREMIER LEAGUE,19.10.2024 09:00,2024/2025,Fulham,Aston Villa,away,list_1,goal,9',Rogers M.,1 - 1,Ramsey J.,None,None,None,JORNADA 8,First Half
4697,298,PREMIER LEAGUE,19.10.2024 09:00,2024/2025,Fulham,Aston Villa,away,list_1,goal,59',Watkins O.,1 - 2,Tielemans Y.,None,None,None,JORNADA 8,Second Half
4699,298,PREMIER LEAGUE,19.10.2024 09:00,2024/2025,Fulham,Aston Villa,away,list_1,goal,69',Diop I.,1 - 3,None,None,None,None,JORNADA 8,Second Half
5216,328,PREMIER LEAGUE,21.09.2024 09:00,2024/2025,Fulham,Newcastle,home,list_0,goal,5',Jiménez R.,1 - 0,Traoré A.,None,None,None,JORNADA 5,First Half
5218,328,PREMIER LEAGUE,21.09.2024 09:00,2024/2025,Fulham,Newcastle,home,list_0,goal,22',Smith Rowe E.,2 - 0,Iwobi A.,None,None,None,JORNADA 5,First Half
5229,328,PREMIER LEAGUE,21.09.2024 09:00,2024/2025,Fulham,Newcastle,home,list_0,goal,90+2',Nelson R.,3 - 1,Rodrigo Muniz,None,None,None,JORNADA 5,Second Half
5232,328,PREMIER LEAGUE,21.09.2024 09:00,2024/2025,Fulham,Newcastle,away,list_1,goal,46',Barnes H.,2 - 1,Murphy J.,None,None,None,JORNADA 5,Second Half
5436,340,PREMIER LEAGUE,14.09.2024 09:00,2024/2025,Fulham,West Ham,home,list_0,goal,24',Jiménez R.,1 - 0,Smith Rowe E.,None,None,None,JORNADA 4,First Half
5452,340,PREMIER LEAGUE,14.09.2024 09:00,2024/2025,Fulham,West Ham,away,list_1,goal,90+5',Ings D.,1 - 1,Bowen J.,None,None,None,JORNADA 4,Second Half
5766,359,PREMIER LEAGUE,24.08.2024 09:00,2024/2025,Fulham,Leicester,home,list_0,goal,18',Smith Rowe E.,1 - 0,Traoré A.,None,None,None,JORNADA 2,First Half
5769,359,PREMIER LEAGUE,24.08.2024 09:00,2024/2025,Fulham,Leicester,home,list_0,goal,70',Iwobi A.,2 - 1,Robinson A.,None,None,None,JORNADA 2,Second Half
5775,359,PREMIER LEAGUE,24.08.2024 09:00,2024/2025,Fulham,Leicester,away,list_1,goal,38',Faes W.,1 - 1,Buonanotte F.,None,None,None,JORNADA 2,First Half